In [1]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# Install Tensorflow from the website: https://www.tensorflow.org/
# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
!curl https://raw.githubusercontent.com/muke888/UdemyDeepLearning/master/1.Artificial%20Neural%20Networks/Churn_Modelling.csv -o Churn_Modelling.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  668k  100  668k    0     0  3327k      0 --:--:-- --:--:-- --:--:-- 3327k


In [2]:
# Importing the dataset, predicting customer churn
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values #exclude first 3 columns as irrelevant
y = dataset.iloc[:, 13].values
dataset.info()
dataset.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
# Encoding categorical data - Geography & Gender
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [4]:
# Encoding Geography to dummy variables as more than 2 categories

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer, make_column_transformer


columntransformer = make_column_transformer(
(OneHotEncoder(categories='auto'), [1]),
    remainder='passthrough'
)
X = columntransformer.fit_transform(X)
X = X[:, 1:] #removing dummy trap
X[0,:]

array([0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

X_train

array([[0.0, 1.0, 667, ..., 1, 0, 163830.64],
       [1.0, 0.0, 427, ..., 1, 1, 57098.0],
       [0.0, 0.0, 535, ..., 1, 0, 185630.76],
       ...,
       [0.0, 0.0, 738, ..., 1, 0, 181429.87],
       [0.0, 1.0, 590, ..., 1, 1, 148750.16],
       [1.0, 0.0, 623, ..., 1, 0, 118855.26]], dtype=object)

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [7]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

Using TensorFlow backend.


In [0]:
# Initialising the ANN
classifier = Sequential()

In [0]:
# Adding the input layer and hidden layers
# Rule of thumb for nodes is average no. features: (11inputs+1output)/2=6
classifier.add(Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform"))

#Optional regularization step, to avoid overfitting, 10% deactivation of nodes
#classifier.add(Dropout(p = 0.1))

# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=6, kernel_initializer="uniform"))
#classifier.add(Dropout(p = 0.1))

# Adding the output layer
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

# Compiling the ANN use 'binary_crossentropy' or 'categorical_crossentropy'
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [10]:
import time

_start_time = time.time()

def tic():
    global _start_time 
    _start_time = time.time()

def tac():
    t_sec = round(time.time() - _start_time)
    (t_min, t_sec) = divmod(t_sec,60)
    (t_hour,t_min) = divmod(t_min,60) 
    print('Time passed: {}hour:{}min:{}sec'.format(t_hour,t_min,t_sec))
    
    
import tensorflow as tf
tf.test.gpu_device_name()
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 5438386162618057772, name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 16722350573120841964
 physical_device_desc: "device: XLA_CPU device"]

In [11]:
# Fitting the ANN to the Training set, using minibatch stochastic gradient descent
tic()

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100, verbose=1,
          validation_data=(X_test, y_test))

tac()

Train on 8000 samples, validate on 2000 samples
Epoch 1/100
8000/8000 [==============================] - 2s 203us/step - loss: 0.4866 - acc: 0.7951 - val_loss: 0.4288 - val_acc: 0.7975
Epoch 2/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4267 - acc: 0.7960 - val_loss: 0.4221 - val_acc: 0.7975
Epoch 3/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4215 - acc: 0.7987 - val_loss: 0.4183 - val_acc: 0.8315
Epoch 4/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.4181 - acc: 0.8249 - val_loss: 0.4133 - val_acc: 0.8300
Epoch 5/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.4160 - acc: 0.8280 - val_loss: 0.4115 - val_acc: 0.8375
Epoch 6/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.4145 - acc: 0.8296 - val_loss: 0.4108 - val_acc: 0.8365
Epoch 7/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.4127 - acc: 0.8322 - val_loss: 0.4064 - val_acc: 

In [12]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [13]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1545,   50],
       [ 268,  137]])

In [14]:
tn, fp, fn, tp = cm.ravel()
#print(tn, fp, fn, tp)
print("Accuracy of:", (tn+tp)/(tn+tp+fp+fn))

# Accuracy = (TP + TN) / (TP + TN + FP + FN)
# Precision = TP / (TP + FP)
# Recall = TP / (TP + FN)
# F1 Score = 2 Precision Recall / (Precision + Recall)

Accuracy of: 0.841


In [15]:
# Predicting a single new observation
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""

'Predict if the customer with the following informations will leave the bank:\nGeography: France\nCredit Score: 600\nGender: Male\nAge: 40\nTenure: 3\nBalance: 60000\nNumber of Products: 2\nHas Credit Card: Yes\nIs Active Member: Yes\nEstimated Salary: 50000'

In [16]:
# Ensure the category labelling matches the transformations made above
test_customer=np.array([[0.0, 0.0, 619, 1, 40, 3, 60000, 2, 1, 1, 50000]])
#test_customer=np.array([0.0, 0.0, 619, 1, 40, 3, 60000, 2, 1, 1, 50000]).reshape(1, -1)
test_customer = sc.transform(test_customer)
test_customer

array([[-0.5698444 , -0.57369368, -0.32524648,  0.91601335,  0.10961719,
        -0.68538967, -0.2569057 ,  0.8095029 ,  0.64259497,  0.9687384 ,
        -0.87203322]])

In [17]:
new_prediction=classifier.predict(test_customer)
new_prediction

array([[0.07668586]], dtype=float32)

In [18]:
new_prediction = (new_prediction > 0.5)
new_prediction 
#Customer does not leave the bank, or probability of leaving is 0.04589

array([[False]])

In [0]:
# Part 4 - Evaluating, Improving and Tuning the ANN

# Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 100)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1) 

In [20]:
print(accuracies)
print(accuracies.mean())
print(accuracies.std())
#If there is high variance between scores, use regularization (eg. dropouts)

[0.85874999 0.83124999 0.83624999 0.83124999 0.85125    0.83125
 0.83624999 0.85       0.83499999 0.83999999]
0.8401249944791196
0.009277829617576935


In [24]:
# Tuning the ANN with randomizedsearchCV

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import RandomizedSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier)
adam=keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
sgd=keras.optimizers.SGD(lr=0.01, momentum=0.9, decay=0.0, nesterov=False)
parameters = {'batch_size': [15, 20, 25],
              'epochs': [600,800],
              'optimizer': [adam,sgd]}


grid_search = RandomizedSearchCV(estimator = classifier,
                           param_distributions = parameters,
                           scoring = 'accuracy',
                           cv = 10, verbose=5,n_iter=4, n_jobs=1) 
grid_search = grid_search.fit(X_train, y_train)


8000/8000 [==============================] - 1s 81us/step - loss: 0.3357 - acc: 0.8645
Epoch 791/800
8000/8000 [==============================] - 1s 80us/step - loss: 0.3345 - acc: 0.8645
Epoch 792/800
8000/8000 [==============================] - 1s 81us/step - loss: 0.3339 - acc: 0.8655
Epoch 793/800
8000/8000 [==============================] - 1s 82us/step - loss: 0.3345 - acc: 0.8650
Epoch 794/800
8000/8000 [==============================] - 1s 82us/step - loss: 0.3329 - acc: 0.8651
Epoch 795/800
8000/8000 [==============================] - 1s 81us/step - loss: 0.3340 - acc: 0.8645
Epoch 796/800
8000/8000 [==============================] - 1s 81us/step - loss: 0.3344 - acc: 0.8648
Epoch 797/800
8000/8000 [==============================] - 1s 80us/step - loss: 0.3363 - acc: 0.8644
Epoch 798/800
8000/8000 [==============================] - 1s 80us/step - loss: 0.3372 - acc: 0.8644
Epoch 799/800
8000/8000 [==============================] - 1s 88us/step - loss: 0.3330 - acc: 0.8670
Epoc

In [25]:
print(grid_search.best_params_)
print(grid_search.best_score_)

{'optimizer': <keras.optimizers.SGD object at 0x7fb1eccc0ac8>, 'epochs': 800, 'batch_size': 15}
0.85925
